# Generated by Django 5.2.14 on 2026-05-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
