# Generated by Django 5.2.14 on 2026-08-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_remove_userprofile_avatar_url_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmember',
            name='episode_count',
            field=models.IntegerField(blank=True, help_text='Episodes this person appeared in. Null means a series-level credit with no episode rollup.', null=True),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='episode_count',
            field=models.IntegerField(blank=True, help_text='Episodes this person worked on. Null means a series-level credit with no episode rollup.', null=True),
        ),
    ]
