# Generated by Django 5.2.14 on 2026-08-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text="0-based position in the source's ranked list.")),
                ('score', models.FloatField()),
                ('shared_people', models.PositiveIntegerField()),
                ('mode', models.CharField(help_text="The source's ladder rung: weighted, estimated, or rating.", max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_edges', to='shows.show')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_edges_in', to='shows.show')),
            ],
            options={
                'ordering': ['source', 'rank'],
                'indexes': [models.Index(fields=['source', 'rank'], name='shows_simil_source__424a4f_idx')],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
