# Generated by Django 5.2.17 on 2026-08-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_similarshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='show',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
