# Generated by Django 5.2.17 on 2026-08-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_alter_show_options_show_trailer_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
