# Generated by Django 5.2.17 on 2026-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_delete_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarshow',
            name='cast_contribution',
            field=models.FloatField(default=0.0, help_text='Share of the score carried by shared cast (ADR-15).'),
        ),
        migrations.AddField(
            model_name='similarshow',
            name='crew_contribution',
            field=models.FloatField(default=0.0, help_text='Share of the score carried by shared crew (ADR-15).'),
        ),
    ]
